local _, addonTable = ...

addonTable.Localize.ColdWeatherFlying = 54197
addonTable.Localize.FastFlightForm = 40120
addonTable.Localize.FlightForm = 33943
addonTable.Localize.AquaForm = 1066
addonTable.Localize.TravelForm = 783
addonTable.Localize.CatForm = 768
addonTable.Localize.GhostWolf = 2645
addonTable.Localize.CrusaderAura = 32223
addonTable.Localize.AspectCheetah = 5118

-- Default to english, localized below if translation is available (see http://wow.curseforge.com/projects/gogomount/localization/)
addonTable.Localize.Zone.TwistingNether = "Twisting Nether"
addonTable.Localize.Zone.TheFrozenSea = "The Frozen Sea"
addonTable.Localize.Zone.AQ40 = "Ahn'Qiraj"
addonTable.Localize.Zone.Dalaran = "Dalaran"
GOGO_SZONE_THEUNDERBELLY = "The Underbelly"
GOGO_SZONE_KRASUSLANDING = "Krasus' Landing"
GOGO_SZONE_THEVIOLETCITADEL = "The Violet Citadel"
addonTable.Localize.Zone.Wintergrasp = "Wintergrasp"
addonTable.Localize.Zone.SholazarBasin = "Sholazar Basin"
addonTable.Localize.Zone.TheStormPeaks = "The Storm Peaks"
GOGO_ZONE_ICECROWN = "Icecrown"
GOGO_ZONE_THEOCULUS = "The Oculus"
GOGO_SKILL_ENGINEERING = "Engineering"
GOGO_SKILL_TAILORING = "Tailoring"
GOGO_SKILL_RIDING = "Riding"
GOGO_STRING_ENABLEAUTODISMOUNT = "Enable automatic dismount"
GOGO_STRING_DRUIDSINGLECLICK = "Single click to shift from form to travel forms"
addonTable.Localize.String.DruidFlightPreference = "Always use flight forms instead of when moving only"
GOGO_STRING_SAMEEPICFLYSPEED = "Consider 310% and 280% mounts the same speed"
GOGO_STRING_DISABLEUNKNOWNMOUNTNOTICES = "Disable unknown mount notices"
GOGO_STRING_UNKNOWNMOUNTFOUND = "An unknown mount has been found in you list of mounts.  Please report this so that it can be added to future versions of GoGoMount."
GOGO_STRING_FAVORITES = "Favorites"
GOGO_STRING_CURRENTZONEFAVORITES = "Current Zone Favorites"
GOGO_STRING_GLOBALFAVORITES = "Global Favorites"
GOGO_STRING_GLOBALPREFERENCES = "Global Preferences"
GOGO_TALENT_FERALSWIFTNESS = "Feral Swiftness"
GOGO_TALENT_IMPROVEDGHOSTWOLF = "Improved Ghost Wolf"